packages:
  - 'apps/*'
  - 'packages/*'
linkWorkspacePackages: true
preferWorkspacePackages: true
allowBuilds:
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
