import { Request, Response, NextFunction } from 'express';
import { z } from 'zod';
import { AppError } from '../middleware/errorHandler.js';
import { listUsersByTenant, createUser, resetPassword, updateUserPassword, getTenantDetails, updateTenantDetails } from '../services/admin.service.js';

export async function listUsersHandler(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { tenantId } = z
      .object({
        tenantId: z.string().uuid('Invalid tenant ID'),
      })
      .parse(req.query);

    const users = await listUsersByTenant(tenantId);

    res.status(200).json({ data: users });
  } catch (error) {
    next(error);
  }
}

export async function createUserHandler(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { tenantId, name, email, role } = z
      .object({
        tenantId: z.string().uuid('Invalid tenant ID'),
        name: z.string().min(1, 'Name is required').max(255, 'Name too long'),
        email: z.string().email('Invalid email'),
        role: z.enum(['owner', 'admin', 'member'], { message: 'Invalid role' }),
      })
      .parse(req.body);

    const result = await createUser(tenantId, { name, email, role });

    res.status(201).json({
      data: {
        user: result.user,
        temporaryPassword: result.temporaryPassword,
      },
    });
  } catch (error) {
    next(error);
  }
}

export async function resetPasswordHandler(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { userId } = z
      .object({
        userId: z.string().uuid('Invalid user ID'),
      })
      .parse(req.params);

    const result = await resetPassword(userId);

    res.status(200).json({
      data: {
        newPassword: result.newPassword,
      },
    });
  } catch (error) {
    next(error);
  }
}

export async function updatePasswordHandler(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { userId } = z
      .object({
        userId: z.string().uuid('Invalid user ID'),
      })
      .parse(req.params);

    const { password } = z
      .object({
        password: z.string().min(1).optional(),
      })
      .parse(req.body);

    const result = await updateUserPassword(userId, password);

    res.status(200).json({
      data: {
        newPassword: result.newPassword,
        wasAutoGenerated: result.wasAutoGenerated,
      },
    });
  } catch (error) {
    next(error);
  }
}

const HEX_COLOR_REGEX = /^#[0-9A-Fa-f]{6}$/;

const updateTenantDetailsSchema = z.object({
  fury_config: z
    .object({
      target_roas: z.number().positive().optional(),
      target_cpa: z.number().positive().optional(),
      target_ctr: z.number().positive().optional(),
      target_budget_utilization: z.number().min(0).max(100).optional(),
    })
    .optional(),
  brand_kit: z
    .object({
      logo_url: z.string().url().nullable().optional(),
      primary_color: z.string().regex(HEX_COLOR_REGEX, 'Cor primária inválida. Use o formato #RRGGBB.').nullable().optional(),
      secondary_color: z.string().regex(HEX_COLOR_REGEX, 'Cor secundária inválida. Use o formato #RRGGBB.').nullable().optional(),
      voice_tone: z.enum(['professional', 'casual', 'urgent', 'premium']).optional(),
    })
    .optional(),
});

export async function getTenantHandler(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id } = z
      .object({
        id: z.string().uuid('Invalid tenant ID'),
      })
      .parse(req.params);

    const result = await getTenantDetails(id);

    res.status(200).json({ data: result });
  } catch (error) {
    next(error);
  }
}

export async function updateTenantHandler(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id } = z
      .object({
        id: z.string().uuid('Invalid tenant ID'),
      })
      .parse(req.params);

    const payload = updateTenantDetailsSchema.parse(req.body);

    const result = await updateTenantDetails(id, payload);

    res.status(200).json({ data: result });
  } catch (error) {
    next(error);
  }
}
