apiVersion: 1

datasources:
  - name: FURY PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: fury_dev
    user: fury
    secureJsonData:
      password: fury_local
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: true
