import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import { db, users, tenants, furyConfig, brandKits, metaConnections, subscriptions, plans, campaigns, performanceScores } from '@fury/db';
import { eq, and, desc } from 'drizzle-orm';
import { AppError } from '../middleware/errorHandler.js';
import { revokeRefreshToken } from './auth.service.js';
import type { UserDTO } from '../lib/shared.js';

const DEFAULT_NOTIFICATION_PREFS = { campanhas: true, performance: true, equipe: false };

function userToDTO(user: any): UserDTO {
  return {
    id: user.id,
    name: user.name ?? null,
    email: user.email,
    role: user.role,
    tenantId: user.tenantId,
    notificationPrefs: (user.notificationPrefs as UserDTO['notificationPrefs']) ?? DEFAULT_NOTIFICATION_PREFS,
    createdAt: user.createdAt,
  };
}

function generateTemporaryPassword(): string {
  return crypto.randomBytes(6).toString('hex').substring(0, 12);
}

export async function listUsersByTenant(tenantId: string): Promise<UserDTO[]> {
  const userList = await db.query.users.findMany({
    where: eq(users.tenantId, tenantId),
  });

  return userList.map(userToDTO);
}

export async function createUser(
  tenantId: string,
  data: { name: string; email: string; role: 'owner' | 'admin' | 'member' },
): Promise<{ user: UserDTO; temporaryPassword: string }> {
  // Check if email already exists in this tenant
  const existingUser = await db.query.users.findFirst({
    where: and(eq(users.email, data.email), eq(users.tenantId, tenantId)),
  });

  if (existingUser) {
    throw new AppError(409, 'EMAIL_EXISTS', 'Email already registered in this tenant');
  }

  // Generate temporary password
  const temporaryPassword = generateTemporaryPassword();
  const passwordHash = await bcrypt.hash(temporaryPassword, 12);

  // Create user
  const [user] = await db
    .insert(users)
    .values({
      tenantId,
      name: data.name,
      email: data.email,
      passwordHash,
      role: data.role,
      isSuperadmin: false,
    })
    .returning();

  // TODO: integrar A2 — enviar email de boas-vindas com temporaryPassword
  // await sendWelcomeEmail(user.email, user.name, temporaryPassword);

  return {
    user: userToDTO(user),
    temporaryPassword,
  };
}

export async function resetPassword(userId: string): Promise<{ newPassword: string }> {
  // Fetch user
  const user = await db.query.users.findFirst({
    where: eq(users.id, userId),
  });

  if (!user) {
    throw new AppError(404, 'USER_NOT_FOUND', 'User not found');
  }

  // Superadmin cannot have password reset via this endpoint
  if (user.isSuperadmin) {
    throw new AppError(403, 'FORBIDDEN', 'Cannot reset superadmin password');
  }

  // Generate new temporary password
  const newPassword = generateTemporaryPassword();
  const passwordHash = await bcrypt.hash(newPassword, 12);

  // Update user password
  await db.update(users).set({ passwordHash }).where(eq(users.id, userId));

  // TODO: integrar A2 — enviar email com newPassword
  // await sendPasswordResetEmail(user.email, user.name, newPassword);

  return {
    newPassword,
  };
}

export async function updateUserPassword(
  userId: string,
  customPassword?: string,
): Promise<{ newPassword: string | null; wasAutoGenerated: boolean }> {
  // Fetch user
  const user = await db.query.users.findFirst({
    where: eq(users.id, userId),
  });

  if (!user) {
    throw new AppError(404, 'USER_NOT_FOUND', 'User not found');
  }

  // Superadmin cannot have password changed via this endpoint
  if (user.isSuperadmin) {
    throw new AppError(403, 'FORBIDDEN', 'Cannot reset superadmin password');
  }

  // Determine password
  const wasAutoGenerated = !customPassword || customPassword.trim() === '';
  const newPassword = wasAutoGenerated ? generateTemporaryPassword() : customPassword!.trim();
  const passwordHash = await bcrypt.hash(newPassword, 12);

  // Update user password
  await db.update(users).set({ passwordHash }).where(eq(users.id, userId));

  // Revoke refresh token
  await revokeRefreshToken(userId);

  // Send email only if password was auto-generated
  if (wasAutoGenerated) {
    // TODO: integrar A2 — enviar email com nova senha
    // await sendPasswordResetEmail(user.email, user.name, newPassword);
  }

  return {
    newPassword: wasAutoGenerated ? newPassword : null,
    wasAutoGenerated,
  };
}

interface TenantDetails {
  subscription: {
    id: string;
    plan_name: string;
    status: string;
    trial_ends_at: Date | null;
    current_period_end: Date | null;
  } | null;
  fury_config: {
    target_roas: number;
    target_cpa: number;
    target_ctr: number;
    target_budget_utilization: number;
  };
  brand_kit: {
    logo_url: string | null;
    primary_color: string | null;
    secondary_color: string | null;
    voice_tone: string | null;
  } | null;
  meta_connection_status: 'not_connected' | 'expired' | 'connected';
}

export async function getTenantDetails(tenantId: string): Promise<TenantDetails> {
  // Verify tenant exists
  const tenant = await db.query.tenants.findFirst({
    where: eq(tenants.id, tenantId),
  });

  if (!tenant) {
    throw new AppError(404, 'TENANT_NOT_FOUND', 'Tenant not found');
  }

  // Fetch subscription with plan (with error handling like billing.routes.ts)
  let subscription: TenantDetails['subscription'] = null;
  try {
    const sub = await db.query.subscriptions.findFirst({
      where: eq(subscriptions.tenantId, tenantId),
      orderBy: [desc(subscriptions.createdAt)],
    });

    if (sub) {
      const plan = await db.query.plans.findFirst({
        where: eq(plans.id, sub.planId),
      });

      if (plan) {
        subscription = {
          id: sub.id,
          plan_name: plan.name,
          status: sub.status,
          trial_ends_at: sub.trialEndsAt,
          current_period_end: sub.currentPeriodEnd,
        };
      }
    }
  } catch (dbErr: any) {
    console.error('[admin] subscriptions query failed:', dbErr?.message ?? dbErr);
  }

  // Fetch or create fury_config
  let config = await db.query.furyConfig.findFirst({
    where: eq(furyConfig.tenantId, tenantId),
  });

  if (!config) {
    [config] = await db.insert(furyConfig).values({ tenantId }).returning();
  }

  // Fetch brand_kit (return null if not exists)
  let brandKit: TenantDetails['brand_kit'] = null;
  const bk = await db.query.brandKits.findFirst({
    where: eq(brandKits.tenantId, tenantId),
  });

  if (bk) {
    brandKit = {
      logo_url: bk.logoUrl ?? null,
      primary_color: bk.primaryColor ?? null,
      secondary_color: bk.secondaryColor ?? null,
      voice_tone: bk.voiceTone ?? null,
    };
  }

  // Fetch meta_connection and derive status (without decrypting token)
  let metaConnectionStatus: TenantDetails['meta_connection_status'] = 'not_connected';
  const metaConn = await db.query.metaConnections.findFirst({
    where: eq(metaConnections.tenantId, tenantId),
  });

  if (metaConn) {
    if (metaConn.tokenExpiresAt && metaConn.tokenExpiresAt < new Date()) {
      metaConnectionStatus = 'expired';
    } else {
      metaConnectionStatus = 'connected';
    }
  }

  return {
    subscription,
    fury_config: {
      target_roas: parseFloat(config.targetRoas),
      target_cpa: parseFloat(config.targetCpa),
      target_ctr: parseFloat(config.targetCtr),
      target_budget_utilization: parseFloat(config.targetBudgetUtilization),
    },
    brand_kit: brandKit,
    meta_connection_status: metaConnectionStatus,
  };
}

export async function updateTenantDetails(
  tenantId: string,
  data: {
    fury_config?: {
      target_roas?: number;
      target_cpa?: number;
      target_ctr?: number;
      target_budget_utilization?: number;
    };
    brand_kit?: {
      logo_url?: string | null;
      primary_color?: string | null;
      secondary_color?: string | null;
      voice_tone?: string | null;
    };
  },
): Promise<TenantDetails> {
  // Verify tenant exists
  const tenant = await db.query.tenants.findFirst({
    where: eq(tenants.id, tenantId),
  });

  if (!tenant) {
    throw new AppError(404, 'TENANT_NOT_FOUND', 'Tenant not found');
  }

  // Update fury_config if provided
  if (data.fury_config) {
    const configUpdates: Record<string, any> = { updatedAt: new Date() };
    if (data.fury_config.target_roas !== undefined) configUpdates.targetRoas = data.fury_config.target_roas.toString();
    if (data.fury_config.target_cpa !== undefined) configUpdates.targetCpa = data.fury_config.target_cpa.toString();
    if (data.fury_config.target_ctr !== undefined) configUpdates.targetCtr = data.fury_config.target_ctr.toString();
    if (data.fury_config.target_budget_utilization !== undefined)
      configUpdates.targetBudgetUtilization = data.fury_config.target_budget_utilization.toString();

    const existing = await db.query.furyConfig.findFirst({
      where: eq(furyConfig.tenantId, tenantId),
    });

    if (existing) {
      await db.update(furyConfig).set(configUpdates).where(eq(furyConfig.tenantId, tenantId));
    } else {
      await db.insert(furyConfig).values({ tenantId, ...configUpdates }).returning();
    }
  }

  // Update brand_kit if provided (upsert with onConflictDoUpdate)
  if (data.brand_kit) {
    const bkUpdates: Record<string, any> = { updatedAt: new Date() };
    if (data.brand_kit.logo_url !== undefined) bkUpdates.logoUrl = data.brand_kit.logo_url;
    if (data.brand_kit.primary_color !== undefined) bkUpdates.primaryColor = data.brand_kit.primary_color;
    if (data.brand_kit.secondary_color !== undefined) bkUpdates.secondaryColor = data.brand_kit.secondary_color;
    if (data.brand_kit.voice_tone !== undefined) bkUpdates.voiceTone = data.brand_kit.voice_tone;

    await db
      .insert(brandKits)
      .values({ tenantId, ...bkUpdates })
      .onConflictDoUpdate({
        target: brandKits.tenantId,
        set: bkUpdates,
      });
  }

  // Return updated details
  return getTenantDetails(tenantId);
}

interface TenantCampaignResponse {
  id: string;
  name: string;
  status: string;
  budget: any;
  performance_grade: string | null;
}

export async function listTenantCampaigns(
  tenantId: string,
  filters?: { status?: 'active' | 'paused' | 'draft'; search?: string }
): Promise<TenantCampaignResponse[]> {
  // Verify tenant exists
  const tenant = await db.query.tenants.findFirst({
    where: eq(tenants.id, tenantId),
  });

  if (!tenant) {
    throw new AppError(404, 'TENANT_NOT_FOUND', 'Tenant not found');
  }

  // Build query conditions
  const conditions = [eq(campaigns.tenantId, tenantId)];

  if (filters?.status) {
    conditions.push(eq(campaigns.status, filters.status));
  }

  // Fetch campaigns
  const campaignsList = await db.query.campaigns.findMany({
    where: and(...conditions),
    orderBy: [desc(campaigns.createdAt)],
  });

  // Filter by search if provided
  let filtered = campaignsList;
  if (filters?.search) {
    const searchLower = filters.search.toLowerCase();
    filtered = campaignsList.filter((c) => c.name.toLowerCase().includes(searchLower));
  }

  // For each campaign, fetch latest performance score
  const result: TenantCampaignResponse[] = await Promise.all(
    filtered.map(async (campaign) => {
      const latestScore = await db.query.performanceScores.findFirst({
        where: eq(performanceScores.campaignId, campaign.id),
        orderBy: [desc(performanceScores.computedAt)],
      });

      return {
        id: campaign.id,
        name: campaign.name,
        status: campaign.status,
        budget: campaign.budget,
        performance_grade: latestScore?.grade ?? null,
      };
    })
  );

  return result;
}

export async function updateTenantCampaign(
  tenantId: string,
  campaignId: string,
  data: { status?: 'draft' | 'active' | 'paused' | 'archived'; budget?: { daily_budget?: number } }
): Promise<TenantCampaignResponse> {
  // Fetch campaign
  const campaign = await db.query.campaigns.findFirst({
    where: eq(campaigns.id, campaignId),
  });

  if (!campaign) {
    throw new AppError(404, 'CAMPAIGN_NOT_FOUND', 'Campaign not found');
  }

  // Verify campaign belongs to tenant
  if (campaign.tenantId !== tenantId) {
    throw new AppError(403, 'FORBIDDEN', 'You do not have access to this resource');
  }

  // Build update object
  const updates: Record<string, any> = {};

  if (data.status) {
    updates.status = data.status;
  }

  if (data.budget) {
    const existingBudget = (campaign.budget as any) || {};
    updates.budget = {
      ...existingBudget,
      ...(data.budget.daily_budget !== undefined && { daily_budget: data.budget.daily_budget }),
    };
  }

  // Update campaign (only if there's something to update)
  if (Object.keys(updates).length > 0) {
    await db.update(campaigns).set(updates).where(eq(campaigns.id, campaignId));
  }

  // Fetch updated campaign
  const updatedCampaign = await db.query.campaigns.findFirst({
    where: eq(campaigns.id, campaignId),
  });

  if (!updatedCampaign) {
    throw new AppError(500, 'INTERNAL_ERROR', 'Failed to fetch updated campaign');
  }

  // Fetch latest performance score
  const latestScore = await db.query.performanceScores.findFirst({
    where: eq(performanceScores.campaignId, campaignId),
    orderBy: [desc(performanceScores.computedAt)],
  });

  return {
    id: updatedCampaign.id,
    name: updatedCampaign.name,
    status: updatedCampaign.status,
    budget: updatedCampaign.budget,
    performance_grade: latestScore?.grade ?? null,
  };
}
